services:
  matos-ui-docs:
    container_name: matos-ui-docs
    build:
      context: .
      dockerfile: Dockerfile
    image: matos-ui/docs:prod
    ports:
      - "127.0.0.1:8080:4000"
    restart: unless-stopped
