import { exec } from "node:child_process";
import { existsSync, promises as fs } from "node:fs";
import path from "node:path";
import { rimraf } from "rimraf";
import { getSiteUrl } from "../lib/site-url";
import { registry } from "../registry";

interface JsonRegistryFile {
  path?: string;
  target?: string;
  content?: string;
  type?: string;
}

interface RegistryFileEntry {
  path: string;
  type: string | undefined;
  target: string;
  content: string;
}

const siteUrl = getSiteUrl();

// copied most of the functions from:
// https://github.com/creativetimofficial/ui/blob/main/apps/www/scripts/build-registry.mts

function runCommand(command: string) {
  return new Promise<void>((resolve, reject) => {
    exec(command, (error, stdout, stderr) => {
      if (stdout) {
        console.log(stdout);
      }

      if (stderr) {
        console.error(stderr);
      }

      if (error) {
        reject(error);
        return;
      }

      resolve();
    });
  });
}

function normalizeLineEndings(content: string) {
  return content.replace(/\r\n/g, "\n");
}

async function formatGeneratedFiles(...files: string[]) {
  await runCommand(`bunx biome format --write ${files.join(" ")}`);
}

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map(
      (file) => `src/registry/new-york-v4/${file.path}`,
    );
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/new-york-v4/${item.files[0].path}`
      : "";

    index += `
  "${item.name}": {
    name: "${item.name}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `src/registry/new-york-v4/${typeof file === "string" ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} items found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"));
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index);
  await formatGeneratedFiles("registry/__index__.tsx");
}

async function buildRegistryJsonFile() {
  // 1. Add registry/new-york-v4 prefix for the build to work
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `src/registry/new-york-v4/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), `registry.json`));
  await fs.writeFile(
    path.join(process.cwd(), `registry.json`),
    JSON.stringify(fixedRegistry, null, 2),
  );

  // 3. Format the registry.json file.
  await formatGeneratedFiles("registry.json");

  // 4. Copy the registry.json to the www/public/r/styles/new-york-v4 directory.
  await fs.cp(
    path.join(process.cwd(), "registry.json"),
    path.join(
      process.cwd(),
      "../docs/public/r/styles/new-york-v4/registry.json",
    ),
    { recursive: true },
  );
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    exec(
      `bunx shadcn build registry.json --output public/r`,
      async (error, stdout, stderr) => {
        if (error) {
          console.error(`Error: ${error.message}`);
          reject(error);
          return;
        }
        if (stderr) {
          console.error(`stderr: ${stderr}`);
        }
        if (stdout) {
          console.log(stdout);
        }

        // Post-process the generated JSON files to remove registry/new-york-v4 prefix
        console.log("📝 Cleaning up paths in generated JSON files...");
        await cleanupGeneratedPaths();

        resolve(undefined);
      },
    );
  });
}

async function cleanupGeneratedPaths() {
  const publicDir = path.join(process.cwd(), "public/r");

  // Get all JSON files in the public/r directory
  const files = await fs.readdir(publicDir);
  const jsonFiles = files.filter((file) => file.endsWith(".json"));

  for (const file of jsonFiles) {
    const filePath = path.join(publicDir, file);
    const content = await fs.readFile(filePath, "utf-8");
    const json = JSON.parse(content);

    // Clean up the paths in the files array
    if (json.files) {
      // Build a mapping of source paths to target paths for this block
      const pathMappings = new Map<string, string>();

      (json.files as JsonRegistryFile[]).forEach((file) => {
        if (typeof file === "object" && file.path && file.target) {
          // Map the source registry path to the target path
          const sourcePath = file.path.replace(
            /^src\/registry\/new-york-v4\//,
            "",
          );
          pathMappings.set(sourcePath, file.target);
        }
      });

      json.files = (json.files as JsonRegistryFile[]).map((file) => {
        if (typeof file === "object" && file.path) {
          // Remove only src/registry/ prefix, keep new-york-v4/ for branding
          let cleanPath = file.path.replace(/^src\/registry\//, "");

          // For UI components, prepend with components/matos-ui/
          if (cleanPath.startsWith("new-york-v4/ui/")) {
            cleanPath = `components/matos-ui/${cleanPath.replace(/^new-york-v4\/ui\//, "")}`;
          }
          // For examples, prepend with components/matos-ui/
          else if (cleanPath.startsWith("new-york-v4/examples/")) {
            cleanPath = `components/matos-ui/${cleanPath.replace(/^new-york-v4\//, "")}`;
          }
          // For blocks, install under components/<slug>/ so relative imports
          // between the block's own files keep resolving after install.
          else if (cleanPath.startsWith("new-york-v4/blocks/")) {
            cleanPath = `components/${cleanPath.replace(/^new-york-v4\/blocks\//, "")}`;
          }

          file.path = cleanPath;
          file.target = cleanPath;

          // Clean up imports in the content field using the path mappings
          if (file.content) {
            file.content = normalizeLineEndings(
              rewriteImports(file.content, pathMappings),
            );
          }
        }
        return file;
      });
    }

    // Write the cleaned JSON back
    await fs.writeFile(filePath, JSON.stringify(json, null, 2));
  }

  console.log(`✨ Cleaned paths in ${jsonFiles.length} files`);
}

function rewriteImports(
  content: string,
  pathMappings: Map<string, string>,
): string {
  // Sort mappings by path length (longest first) to handle more specific paths first
  const sortedMappings = Array.from(pathMappings.entries()).sort(
    ([a], [b]) => b.length - a.length,
  );

  // Handle block-specific imports using the exact path mappings
  sortedMappings.forEach(([sourcePath, targetPath]) => {
    if (sourcePath.startsWith("blocks/")) {
      // Remove the file extension from sourcePath to match import statements
      const sourcePathNoExt = sourcePath.replace(/\.(tsx?|jsx?)$/, "");

      // Extract the directory from the target path (removing filename)
      const targetPathNoExt = targetPath.replace(/\.(tsx?|jsx?)$/, "");

      // Create regex to match this specific import path
      const escapedPath = sourcePathNoExt.replace(/\//g, "\\/");
      const importRegex = new RegExp(
        `@\\/registry\\/new-york-v4\\/${escapedPath}`,
        "g",
      );

      content = content.replace(importRegex, `@/${targetPathNoExt}`);
    }
  });

  // Rewrite imports from @/registry/new-york-v4/ui/... to @/components/matos-ui/...
  content = content.replace(
    /@\/registry\/new-york-v4\/ui\//g,
    "@/components/matos-ui/",
  );

  // Rewrite imports from @/registry/new-york-v4/examples/... to @/components/matos-ui/examples/...
  content = content.replace(
    /@\/registry\/new-york-v4\/examples\//g,
    "@/components/matos-ui/examples/",
  );

  // Rewrite imports from @/registry/new-york-v4/lib/... to @/lib/...
  content = content.replace(/@\/registry\/new-york-v4\/lib\//g, "@/lib/");

  // Keep command examples aligned with current environment URL.
  content = content.replace(/https:\/\/matos-ui\.(vercel\.app|com)/g, siteUrl);

  return content;
}

async function buildPackageJson(
  packageType: "ui" | "blocks" | "agents",
  fileName: string,
  description: string,
) {
  console.log(`🎨 Building ${fileName} for ${packageType}...`);

  // Filter components by type
  const typeMap = {
    ui: "registry:ui",
    blocks: "registry:block",
    agents: "registry:agent",
  };

  const components = registry.items.filter(
    (item) => item.type === typeMap[packageType],
  );

  // Aggregate all dependencies and registryDependencies
  const allDependencies = new Set<string>();
  const allFiles: RegistryFileEntry[] = [];

  // Build path mappings for import rewriting
  const pathMappings = new Map<string, string>();

  for (const component of components) {
    // Collect dependencies
    if (component.dependencies) {
      for (const dep of component.dependencies) {
        allDependencies.add(dep);
      }
    }

    // Collect registryDependencies

    // Collect files and read their content
    if (component.files) {
      for (const file of component.files) {
        const filePath = `src/registry/new-york-v4/${file.path}`;
        const absolutePath = path.join(process.cwd(), filePath);

        // Read file content
        let content = "";
        if (existsSync(absolutePath)) {
          content = normalizeLineEndings(
            await fs.readFile(absolutePath, "utf-8"),
          );
        }

        // Clean path - remove registry/new-york-v4/ prefix for UI components
        let cleanPath = file.path;
        if (packageType === "ui") {
          if (cleanPath.startsWith("ui/")) {
            cleanPath = `components/matos-ui/${cleanPath.replace(/^ui\//, "")}`;
          } else if (cleanPath.startsWith("examples/")) {
            cleanPath = `components/matos-ui/${cleanPath}`;
          }
        }

        // Build path mapping
        if (file.target) {
          pathMappings.set(file.path, file.target);
        }

        allFiles.push({
          path: cleanPath,
          type: file.type,
          target: cleanPath,
          content: content,
        });
      }
    }
  }

  // Rewrite imports in all file contents
  allFiles.forEach((file) => {
    if (file.content) {
      file.content = rewriteImports(file.content, pathMappings);
    }
  });

  // Create the JSON structure
  const packageJson = {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: fileName.replace(".json", ""),
    type: typeMap[packageType],
    description: description,
    dependencies: Array.from(allDependencies).sort(),
    registryDependencies: [],
    files: allFiles,
  };

  // Write the JSON file
  const outputPath = path.join(process.cwd(), "public", "r", fileName);
  await fs.writeFile(outputPath, JSON.stringify(packageJson, null, 2));

  console.log(
    `✨ Generated ${fileName} with ${components.length} ${packageType} components`,
  );
}

async function buildAllJson() {
  console.log("📦 Building all.json...");

  // Combine all components
  const allDependencies = new Set<string>();
  const allFiles: RegistryFileEntry[] = [];
  const pathMappings = new Map<string, string>();

  for (const component of registry.items) {
    if (component.dependencies) {
      for (const dep of component.dependencies) {
        allDependencies.add(dep);
      }
    }

    if (component.files) {
      for (const file of component.files) {
        const filePath = `src/registry/new-york-v4/${file.path}`;
        const absolutePath = path.join(process.cwd(), filePath);

        let content = "";
        if (existsSync(absolutePath)) {
          content = normalizeLineEndings(
            await fs.readFile(absolutePath, "utf-8"),
          );
        }

        let cleanPath = file.path;
        if (component.type === "registry:ui") {
          if (cleanPath.startsWith("ui/")) {
            cleanPath = `components/matos-ui/${cleanPath.replace(/^ui\//, "")}`;
          } else if (cleanPath.startsWith("examples/")) {
            cleanPath = `components/matos-ui/${cleanPath}`;
          }
        }

        if (file.target) {
          pathMappings.set(file.path, file.target);
        }

        allFiles.push({
          path: cleanPath,
          type: file.type,
          target: cleanPath,
          content: content,
        });
      }
    }
  }

  allFiles.forEach((file) => {
    if (file.content) {
      file.content = rewriteImports(file.content, pathMappings);
    }
  });

  const allJson = {
    $schema: "https://ui.shadcn.com/schema/registry-item.json",
    name: "all",
    type: "registry:item",
    description:
      "All components from Matos UI (UI components, blocks, and agents)",
    dependencies: Array.from(allDependencies).sort(),
    registryDependencies: [],
    files: allFiles,
  };

  // Write to public/r/all.json
  const outputPath = path.join(process.cwd(), "public/r/all.json");
  await fs.writeFile(outputPath, JSON.stringify(allJson, null, 2));

  console.log(
    `✨ Generated all.json with ${registry.items.length} total components`,
  );
}

async function buildPackageRegistries() {
  console.log("📦 Building package-specific registries...");

  // Build UI components registry
  await buildPackageJson(
    "ui",
    "ui.json",
    "All UI components from @matos-ui/ui",
  );

  await buildPackageJson(
    "blocks",
    "blocks.json",
    "All blocks from @matos-ui/blocks",
  );
}

try {
  console.log("🗂️ Building registry/__index__.tsx...");
  await buildRegistryIndex();

  console.log("💅 Building registry.json...");
  await buildRegistryJsonFile();

  console.log("🏗️ Building registry...");
  await buildRegistry();

  console.log("📦 Building package registries...");
  await buildPackageRegistries();

  console.log("📦 Building all.json...");
  await buildAllJson();
} catch (error) {
  console.error(error);
  process.exit(1);
}
