/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  index: {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  style: {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  button: {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  badge: {
    name: "badge",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/badge.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/badge.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  divider: {
    name: "divider",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/divider.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/divider.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  accordion: {
    name: "accordion",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/accordion.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/accordion.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/button-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-demo": {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/badge-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/badge-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "divider-demo": {
    name: "divider-demo",
    type: "registry:example",
    registryDependencies: ["divider"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/divider-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/divider-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "accordion-demo": {
    name: "accordion-demo",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/accordion-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/accordion-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
};
