/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  index: {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  style: {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  button: {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  badge: {
    name: "badge",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/badge.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/badge.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  divider: {
    name: "divider",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/divider.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/divider.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  accordion: {
    name: "accordion",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/accordion.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/accordion.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "action-bar": {
    name: "action-bar",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/action-bar.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/action-bar.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "detail-panel": {
    name: "detail-panel",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/detail-panel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/detail-panel.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  switch: {
    name: "switch",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/switch.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/switch.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "file-upload": {
    name: "file-upload",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/file-upload.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/file-upload.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "notification-stack": {
    name: "notification-stack",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/notification-stack.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/notification-stack.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "metric-card": {
    name: "metric-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/metric-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/metric-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "feedback-card": {
    name: "feedback-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/feedback-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/feedback-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spotlight-card": {
    name: "spotlight-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/spotlight-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/spotlight-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "kinetic-card": {
    name: "kinetic-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/kinetic-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/kinetic-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/button-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-demo": {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/badge-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/badge-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "divider-demo": {
    name: "divider-demo",
    type: "registry:example",
    registryDependencies: ["divider"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/divider-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/divider-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "accordion-demo": {
    name: "accordion-demo",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/accordion-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/accordion-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "action-bar-demo": {
    name: "action-bar-demo",
    type: "registry:example",
    registryDependencies: ["action-bar"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/action-bar-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/action-bar-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "detail-panel-demo": {
    name: "detail-panel-demo",
    type: "registry:example",
    registryDependencies: ["detail-panel", "button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/detail-panel-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/detail-panel-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "switch-demo": {
    name: "switch-demo",
    type: "registry:example",
    registryDependencies: ["switch"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/switch-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/switch-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "file-upload-demo": {
    name: "file-upload-demo",
    type: "registry:example",
    registryDependencies: ["file-upload"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/file-upload-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/file-upload-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "notification-stack-demo": {
    name: "notification-stack-demo",
    type: "registry:example",
    registryDependencies: ["notification-stack", "button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/notification-stack-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/notification-stack-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "metric-card-demo": {
    name: "metric-card-demo",
    type: "registry:example",
    registryDependencies: ["metric-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/metric-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/metric-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "feedback-card-demo": {
    name: "feedback-card-demo",
    type: "registry:example",
    registryDependencies: ["feedback-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/feedback-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/feedback-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    type: "registry:example",
    registryDependencies: ["spotlight-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/spotlight-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/spotlight-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "kinetic-card-demo": {
    name: "kinetic-card-demo",
    type: "registry:example",
    registryDependencies: ["kinetic-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/kinetic-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/kinetic-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
};
