/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react";
// biome-ignore lint/suspicious/noExplicitAny: autogenerated file
export const Index: Record<string, any> = {
  index: {
    name: "index",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  style: {
    name: "style",
    type: "registry:style",
    registryDependencies: ["utils"],
    files: [],
    component: null,
  },
  button: {
    name: "button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "reactive-button": {
    name: "reactive-button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/reactive-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/reactive-button.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "theme-toggler-button": {
    name: "theme-toggler-button",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/theme-toggler-button.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/theme-toggler-button.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  badge: {
    name: "badge",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/badge.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/badge.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "data-table": {
    name: "data-table",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/data-table.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/data-table.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "activity-feed": {
    name: "activity-feed",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/activity-feed.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/activity-feed.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "status-pulse-card": {
    name: "status-pulse-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/status-pulse-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/status-pulse-card.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "inset-command-dock": {
    name: "inset-command-dock",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/inset-command-dock.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/inset-command-dock.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dynamic-island": {
    name: "dynamic-island",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/dynamic-island.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/dynamic-island.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  accordion: {
    name: "accordion",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/accordion.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/accordion.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "action-bar": {
    name: "action-bar",
    type: "registry:ui",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/action-bar.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/action-bar.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "detail-panel": {
    name: "detail-panel",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/detail-panel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/detail-panel.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "command-dock": {
    name: "command-dock",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/command-dock.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/command-dock.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "file-upload": {
    name: "file-upload",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/file-upload.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/file-upload.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "notification-stack": {
    name: "notification-stack",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/notification-stack.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/notification-stack.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "metric-card": {
    name: "metric-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/metric-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/metric-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "animated-area-chart": {
    name: "animated-area-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/animated-area-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/animated-area-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "allocation-performance-chart": {
    name: "allocation-performance-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/allocation-performance-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/allocation-performance-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "sparkline-card": {
    name: "sparkline-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/sparkline-card.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/sparkline-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "signal-flow-chart": {
    name: "signal-flow-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/signal-flow-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/signal-flow-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "activity-heatmap-chart": {
    name: "activity-heatmap-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/activity-heatmap-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/activity-heatmap-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "candlestick-chart": {
    name: "candlestick-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/candlestick-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/candlestick-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bubble-chart": {
    name: "bubble-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/bubble-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/bubble-chart.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "activity-waveform-chart": {
    name: "activity-waveform-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/activity-waveform-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/activity-waveform-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "performance-waterfall-chart": {
    name: "performance-waterfall-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/performance-waterfall-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/performance-waterfall-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "threshold-band-chart": {
    name: "threshold-band-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/threshold-band-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/threshold-band-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "impact-priority-matrix": {
    name: "impact-priority-matrix",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/impact-priority-matrix.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/impact-priority-matrix.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "resource-treemap-chart": {
    name: "resource-treemap-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/resource-treemap-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/resource-treemap-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "score-radar-chart": {
    name: "score-radar-chart",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/score-radar-chart.tsx",
        type: "registry:ui",
        target: "",
      },
      {
        path: "src/registry/new-york-v4/ui/chart-interaction.ts",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/score-radar-chart.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "motion-tabs": {
    name: "motion-tabs",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/motion-tabs.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/motion-tabs.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "feedback-card": {
    name: "feedback-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/feedback-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/feedback-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spotlight-card": {
    name: "spotlight-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/spotlight-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/spotlight-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "kinetic-card": {
    name: "kinetic-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/kinetic-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/kinetic-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "progress-orbit": {
    name: "progress-orbit",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/progress-orbit.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/progress-orbit.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "process-timeline-engine": {
    name: "process-timeline-engine",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/process-timeline-engine.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/ui/process-timeline-engine.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  field: {
    name: "field",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/field.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/field.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  input: {
    name: "input",
    type: "registry:ui",
    registryDependencies: ["field"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/input.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/input.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "password-input": {
    name: "password-input",
    type: "registry:ui",
    registryDependencies: ["field", "input"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/password-input.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/password-input.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  select: {
    name: "select",
    type: "registry:ui",
    registryDependencies: ["field"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/select.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/select.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  textarea: {
    name: "textarea",
    type: "registry:ui",
    registryDependencies: ["field"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/textarea.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/textarea.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "form-grid": {
    name: "form-grid",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/form-grid.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/form-grid.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "form-section": {
    name: "form-section",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/form-section.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/form-section.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  checkbox: {
    name: "checkbox",
    type: "registry:ui",
    registryDependencies: ["field"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/checkbox.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/checkbox.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "otp-input": {
    name: "otp-input",
    type: "registry:ui",
    registryDependencies: ["field"],
    files: [
      {
        path: "src/registry/new-york-v4/ui/otp-input.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/otp-input.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "popover-card": {
    name: "popover-card",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/popover-card.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/popover-card.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "sheet-panel": {
    name: "sheet-panel",
    type: "registry:ui",
    registryDependencies: undefined,
    files: [
      {
        path: "src/registry/new-york-v4/ui/sheet-panel.tsx",
        type: "registry:ui",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import("@/registry/new-york-v4/ui/sheet-panel.tsx");
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "button-demo": {
    name: "button-demo",
    type: "registry:example",
    registryDependencies: ["button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/button-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "reactive-button-demo": {
    name: "reactive-button-demo",
    type: "registry:example",
    registryDependencies: ["reactive-button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/reactive-button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/reactive-button-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "theme-toggler-button-demo": {
    name: "theme-toggler-button-demo",
    type: "registry:example",
    registryDependencies: ["theme-toggler-button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/theme-toggler-button-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/theme-toggler-button-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "badge-demo": {
    name: "badge-demo",
    type: "registry:example",
    registryDependencies: ["badge"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/badge-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/badge-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "data-table-demo": {
    name: "data-table-demo",
    type: "registry:example",
    registryDependencies: ["data-table"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/data-table-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/data-table-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "activity-feed-demo": {
    name: "activity-feed-demo",
    type: "registry:example",
    registryDependencies: ["activity-feed"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/activity-feed-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/activity-feed-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "status-pulse-card-demo": {
    name: "status-pulse-card-demo",
    type: "registry:example",
    registryDependencies: ["status-pulse-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/status-pulse-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/status-pulse-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "inset-command-dock-demo": {
    name: "inset-command-dock-demo",
    type: "registry:example",
    registryDependencies: ["inset-command-dock"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/inset-command-dock-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/inset-command-dock-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "dynamic-island-demo": {
    name: "dynamic-island-demo",
    type: "registry:example",
    registryDependencies: ["dynamic-island"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/dynamic-island-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/dynamic-island-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "accordion-demo": {
    name: "accordion-demo",
    type: "registry:example",
    registryDependencies: ["accordion"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/accordion-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/accordion-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "action-bar-demo": {
    name: "action-bar-demo",
    type: "registry:example",
    registryDependencies: ["action-bar"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/action-bar-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/action-bar-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "detail-panel-demo": {
    name: "detail-panel-demo",
    type: "registry:example",
    registryDependencies: ["detail-panel", "button"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/detail-panel-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/detail-panel-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "command-dock-demo": {
    name: "command-dock-demo",
    type: "registry:example",
    registryDependencies: ["command-dock"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/command-dock-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/command-dock-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "file-upload-demo": {
    name: "file-upload-demo",
    type: "registry:example",
    registryDependencies: ["file-upload"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/file-upload-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/file-upload-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "notification-stack-demo": {
    name: "notification-stack-demo",
    type: "registry:example",
    registryDependencies: ["notification-stack"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/notification-stack-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/notification-stack-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "metric-card-demo": {
    name: "metric-card-demo",
    type: "registry:example",
    registryDependencies: ["metric-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/metric-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/metric-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "animated-area-chart-demo": {
    name: "animated-area-chart-demo",
    type: "registry:example",
    registryDependencies: ["animated-area-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/animated-area-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/animated-area-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "allocation-performance-chart-demo": {
    name: "allocation-performance-chart-demo",
    type: "registry:example",
    registryDependencies: ["allocation-performance-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/allocation-performance-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/allocation-performance-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "sparkline-card-demo": {
    name: "sparkline-card-demo",
    type: "registry:example",
    registryDependencies: ["sparkline-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/sparkline-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/sparkline-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "signal-flow-chart-demo": {
    name: "signal-flow-chart-demo",
    type: "registry:example",
    registryDependencies: ["signal-flow-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/signal-flow-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/signal-flow-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "activity-heatmap-chart-demo": {
    name: "activity-heatmap-chart-demo",
    type: "registry:example",
    registryDependencies: ["activity-heatmap-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/activity-heatmap-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/activity-heatmap-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "candlestick-chart-demo": {
    name: "candlestick-chart-demo",
    type: "registry:example",
    registryDependencies: ["candlestick-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/candlestick-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/candlestick-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "bubble-chart-demo": {
    name: "bubble-chart-demo",
    type: "registry:example",
    registryDependencies: ["bubble-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/bubble-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/bubble-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "activity-waveform-chart-demo": {
    name: "activity-waveform-chart-demo",
    type: "registry:example",
    registryDependencies: ["activity-waveform-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/activity-waveform-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/activity-waveform-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "performance-waterfall-chart-demo": {
    name: "performance-waterfall-chart-demo",
    type: "registry:example",
    registryDependencies: ["performance-waterfall-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/performance-waterfall-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/performance-waterfall-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "threshold-band-chart-demo": {
    name: "threshold-band-chart-demo",
    type: "registry:example",
    registryDependencies: ["threshold-band-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/threshold-band-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/threshold-band-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "impact-priority-matrix-demo": {
    name: "impact-priority-matrix-demo",
    type: "registry:example",
    registryDependencies: ["impact-priority-matrix"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/impact-priority-matrix-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/impact-priority-matrix-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "resource-treemap-chart-demo": {
    name: "resource-treemap-chart-demo",
    type: "registry:example",
    registryDependencies: ["resource-treemap-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/resource-treemap-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/resource-treemap-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "score-radar-chart-demo": {
    name: "score-radar-chart-demo",
    type: "registry:example",
    registryDependencies: ["score-radar-chart"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/score-radar-chart-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/score-radar-chart-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "motion-tabs-demo": {
    name: "motion-tabs-demo",
    type: "registry:example",
    registryDependencies: ["motion-tabs"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/motion-tabs-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/motion-tabs-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "feedback-card-demo": {
    name: "feedback-card-demo",
    type: "registry:example",
    registryDependencies: ["feedback-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/feedback-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/feedback-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "progress-orbit-demo": {
    name: "progress-orbit-demo",
    type: "registry:example",
    registryDependencies: ["progress-orbit"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/progress-orbit-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/progress-orbit-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "spotlight-card-demo": {
    name: "spotlight-card-demo",
    type: "registry:example",
    registryDependencies: ["spotlight-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/spotlight-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/spotlight-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "kinetic-card-demo": {
    name: "kinetic-card-demo",
    type: "registry:example",
    registryDependencies: ["kinetic-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/kinetic-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/kinetic-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "process-timeline-engine-demo": {
    name: "process-timeline-engine-demo",
    type: "registry:example",
    registryDependencies: ["process-timeline-engine"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/process-timeline-engine-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/process-timeline-engine-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "input-demo": {
    name: "input-demo",
    type: "registry:example",
    registryDependencies: ["input"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/input-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/input-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "password-input-demo": {
    name: "password-input-demo",
    type: "registry:example",
    registryDependencies: ["password-input"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/password-input-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/password-input-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "select-demo": {
    name: "select-demo",
    type: "registry:example",
    registryDependencies: ["select"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/select-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/select-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "textarea-demo": {
    name: "textarea-demo",
    type: "registry:example",
    registryDependencies: ["textarea"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/textarea-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/textarea-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "checkbox-demo": {
    name: "checkbox-demo",
    type: "registry:example",
    registryDependencies: ["checkbox"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/checkbox-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/checkbox-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "form-grid-demo": {
    name: "form-grid-demo",
    type: "registry:example",
    registryDependencies: ["input", "textarea", "form-grid", "form-section"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/form-grid-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/form-grid-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "form-with-zod-demo": {
    name: "form-with-zod-demo",
    type: "registry:example",
    registryDependencies: [
      "button",
      "input",
      "select",
      "form-grid",
      "form-section",
    ],
    files: [
      {
        path: "src/registry/new-york-v4/examples/form-with-zod-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/form-with-zod-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "otp-input-demo": {
    name: "otp-input-demo",
    type: "registry:example",
    registryDependencies: ["otp-input"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/otp-input-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/otp-input-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "popover-card-demo": {
    name: "popover-card-demo",
    type: "registry:example",
    registryDependencies: ["popover-card"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/popover-card-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/popover-card-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "sheet-panel-demo": {
    name: "sheet-panel-demo",
    type: "registry:example",
    registryDependencies: ["sheet-panel"],
    files: [
      {
        path: "src/registry/new-york-v4/examples/sheet-panel-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/sheet-panel-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
  "signup-form-demo": {
    name: "signup-form-demo",
    type: "registry:example",
    registryDependencies: [
      "button",
      "checkbox",
      "form-grid",
      "form-section",
      "input",
      "password-input",
      "select",
      "textarea",
    ],
    files: [
      {
        path: "src/registry/new-york-v4/examples/signup-form-demo.tsx",
        type: "registry:example",
        target: "",
      },
    ],
    component: React.lazy(async () => {
      const mod = await import(
        "@/registry/new-york-v4/examples/signup-form-demo.tsx"
      );
      const exportName =
        Object.keys(mod).find(
          (key) =>
            typeof mod[key] === "function" || typeof mod[key] === "object",
        ) || item.name;
      return { default: mod.default || mod[exportName] };
    }),
  },
};
